import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import SideNav from '@/components/SideNav';
import ClientProvider from '@/components/ClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: 'WorkInn | %s',
    default: 'WorkInn | Your Freelancing Platform',
  },
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  themeColor: '#ffffff',
  category: 'freelance',

  openGraph: {
    type: 'website',
    title: {
      template: 'WorkInn | %s',
      default: 'WorkInn | Your Freelancing Platform',
    },
    description: 'Generated by create next app',
    images: [
      {
        url: '/WrokInn Logo.svg',
        width: 512,
        height: 512,
        alt: 'WorkInn Logo',
      },
      {
        url: '/WrokInn Logo Dark.svg',
        width: 512,
        height: 512,
        alt: 'WorkInn Logo Dark',
      },
    ],
    locale: 'en_US',
    countryName: 'India',
    siteName: 'WorkInn',
    emails: ['shivangmishra0824@gmail.com'],
    phoneNumbers: [],
  },

  twitter: {
    card: 'summary_large_image',
    title: {
      template: 'WorkInn | %s',
      default: 'WorkInn | Your Freelancing Platform',
    },
    description: 'Generated by create next app',
    siteId: '1467726470533754880',
    creator: '@nextjs',
    creatorId: '1467726470533754880',
    images: [
      {
        url: '/WrokInn Logo.svg',
        width: 512,
        height: 512,
        alt: 'WorkInn Logo',
      },
      {
        url: '/WrokInn Logo Dark.svg',
        width: 512,
        height: 512,
        alt: 'WorkInn Logo Dark',
      },
    ],
    site: '',
  },

  authors: [
    {
      name: 'Pranay Thakre',
      url: 'https://www.linkedin.com/in/pranay-thakre-702a7a1b8/',
    },
    {
      name: 'Shivangini Kumar',
      url: 'https://www.linkedin.com/in/shivangini-kumar-72a07821b/',
    },
    {
      name: 'Shivang Mishra',
      url: 'https://www.shivangmishra.tech/',
    },
  ],
  applicationName: 'WorkInn',
  colorScheme: 'only light',
  generator: 'WorkInn',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={inter.style} className="relative">
        <ClientProvider>
          <Navbar />
          <SideNav />
          <ToastContainer position="bottom-right" />
          {children}
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
